version: '3.8'

services:
  frontend:
    image: tharun9705/movie_recommendation_frontend_server
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      - backend

  backend:
    image: tharun9705/movie_recommendation_backend_server
    ports:
      - "5015:5015"
    networks:
      - my-network
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: my_database
      MYSQL_ROOT_PASSWORD: secret-pw
    volumes:
      - mysqlvolume-data:/var/lib/mysql
    networks:
      - my-network

volumes:
  mysqlvolume-data:

networks:
  my-network:
    driver: bridge

